#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01b/kumamoto_landslide_warning_zones_2025_preprocessed.parquet
Output: data/processed/landslide_zones_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01b/kumamoto_landslide_warning_zones_2025_preprocessed.parquet"
dst = ROOT / "data/processed/landslide_zones_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Hazard Type Code": "Hazard Type Code",
    "Warning Zone Class Code": "Warning Zone Class Code",
    "Zone ID": "Zone ID",
    "Special Warning Zone Pending Code": "Special Warning Zone Pending Code",
    "Geometry": "Geometry",
    "Hazard Type": "Hazard Type",
    "Warning Zone Class": "Warning Zone Class",
    "Special Warning Zone Pending": "Special Warning Zone Pending",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Zone ID
df["Zone ID"] = df["Zone ID"].str.strip()
# Hazard Type
df["Hazard Type"] = df["Hazard Type"].str.strip()
# Warning Zone Class
df["Warning Zone Class"] = df["Warning Zone Class"].str.strip()
# Special Warning Zone Pending
df["Special Warning Zone Pending"] = df["Special Warning Zone Pending"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
