#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01/kumamoto_mlit_welfare_facilities_preprocessed.parquet
Output: data/processed/welfare_facilities_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01/kumamoto_mlit_welfare_facilities_preprocessed.parquet"
dst = ROOT / "data/processed/welfare_facilities_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Support Facility ID": "Welfare Facility ID",
    "Welfare Facility Major Class": "Welfare Facility Major Class",
    "Welfare Facility Medium Class": "Welfare Facility Medium Class",
    "Welfare Facility Minor Class": "Welfare Facility Minor Class",
    "Facility Name": "Welfare Facility Name",
    "Position Accuracy": "Position Accuracy",
    "geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Welfare Facility ID
df["Welfare Facility ID"] = df["Welfare Facility ID"].str.strip()
# Welfare Facility Major Class
df["Welfare Facility Major Class"] = df["Welfare Facility Major Class"].str.strip()
# Welfare Facility Medium Class
df["Welfare Facility Medium Class"] = df["Welfare Facility Medium Class"].str.strip()
# Welfare Facility Minor Class
df["Welfare Facility Minor Class"] = df["Welfare Facility Minor Class"].str.strip()
# Welfare Facility Name
df["Welfare Facility Name"] = df["Welfare Facility Name"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
