#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01/kumamoto_housing_damage_snapshots_preprocessed.parquet
Output: data/processed/housing_damage_reference_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01/kumamoto_housing_damage_snapshots_preprocessed.parquet"
dst = ROOT / "data/processed/housing_damage_reference_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Snapshot ID": "Snapshot ID",
    "Observation Time": "Observation Time",
    "Geographic Level": "Geographic Level",
    "Municipality": "Municipality",
    "Full Collapse Buildings": "Full Collapse Buildings",
    "Half Collapse Buildings": "Half Collapse Buildings",
    "Partial Damage Buildings": "Partial Damage Buildings",
    "Reported Affected Buildings": "Reported Affected Buildings",
    "Data Status": "Data Status",
    "Source Organization": "Source Organization",
    "Source Report Number": "Source Report Number",
    "Source URL": "Source URL",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Snapshot ID
df["Snapshot ID"] = df["Snapshot ID"].str.strip()
# Geographic Level
df["Geographic Level"] = df["Geographic Level"].str.strip()
# Municipality
df["Municipality"] = df["Municipality"].str.strip()
# Data Status
df["Data Status"] = df["Data Status"].str.strip()
# Source Organization
df["Source Organization"] = df["Source Organization"].str.strip()
# Source URL
df["Source URL"] = df["Source URL"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
