#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01/kumamoto_mlit_schools_preprocessed.parquet
Output: data/processed/schools_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01/kumamoto_mlit_schools_preprocessed.parquet"
dst = ROOT / "data/processed/schools_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Support Facility ID": "School Facility ID",
    "School Code": "School Code",
    "School Class": "School Class",
    "Facility Name": "School Name",
    "Suspension Status": "Suspension Status",
    "geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# School Facility ID
df["School Facility ID"] = df["School Facility ID"].str.strip()
# School Code
df["School Code"] = df["School Code"].str.strip()
# School Class
df["School Class"] = df["School Class"].str.strip()
# School Name
df["School Name"] = df["School Name"].str.strip()
# Suspension Status
df["Suspension Status"] = df["Suspension Status"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
