#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01/kumamoto_mlit_public_offices_halls_preprocessed.parquet
Output: data/processed/public_facilities_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01/kumamoto_mlit_public_offices_halls_preprocessed.parquet"
dst = ROOT / "data/processed/public_facilities_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Support Facility ID": "Public Facility ID",
    "Facility Class": "Public Facility Class",
    "Facility Name": "Public Facility Name",
    "geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Public Facility ID
df["Public Facility ID"] = df["Public Facility ID"].str.strip()
# Public Facility Class
df["Public Facility Class"] = df["Public Facility Class"].str.strip()
# Public Facility Name
df["Public Facility Name"] = df["Public Facility Name"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
