#!/usr/bin/env python3
"""Preprocessing script for ../KE01b/data/processed/kumamoto_routable_road_edges_preprocessed.parquet
Output: data/processed/routable_road_edges_sectioned_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "../KE01b/data/processed/kumamoto_routable_road_edges_preprocessed.parquet"
dst = ROOT / "data/processed/routable_road_edges_sectioned_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Road Edge ID": "Road Edge ID",
    "Road Section ID": "Road Section ID",
    "From Node ID": "From Node ID",
    "To Node ID": "To Node ID",
    "Network Component ID": "Network Component ID",
    "Road Length (m)": "Road Length (m)",
    "Assumed Speed (km/h)": "Assumed Speed (km/h)",
    "Baseline Edge Travel Time (min)": "Baseline Edge Travel Time (min)",
    "Hazard Exposure Class": "Hazard Exposure Class",
    "Emergency Route Membership": "Emergency Route Membership",
    "Road Available": "Road Available",
    "Network Analysis Eligible": "Network Analysis Eligible",
    "Route ID": "Route ID",
    "Route Name": "Route Name",
    "Road Category": "Road Category",
    "Road State": "Road State",
    "Vertical Level": "Vertical Level",
    "Width Category": "Width Category",
    "Toll Category": "Toll Category",
    "Secondary Mesh Code": "Secondary Mesh Code",
    "Geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Road Edge ID
df["Road Edge ID"] = df["Road Edge ID"].str.strip()
# Road Section ID
df["Road Section ID"] = df["Road Section ID"].str.strip()
# From Node ID
df["From Node ID"] = df["From Node ID"].str.strip()
# To Node ID
df["To Node ID"] = df["To Node ID"].str.strip()
# Network Component ID
df["Network Component ID"] = df["Network Component ID"].str.strip()
# Hazard Exposure Class
df["Hazard Exposure Class"] = df["Hazard Exposure Class"].str.strip()
# Emergency Route Membership
df["Emergency Route Membership"] = df["Emergency Route Membership"].str.strip()
# Route ID
df["Route ID"] = df["Route ID"].str.strip()
# Route Name
df["Route Name"] = df["Route Name"].str.strip()
# Road Category
df["Road Category"] = df["Road Category"].str.strip()
# Road State
df["Road State"] = df["Road State"].str.strip()
# Width Category
df["Width Category"] = df["Width Category"].str.strip()
# Toll Category
df["Toll Category"] = df["Toll Category"].str.strip()
# Secondary Mesh Code
df["Secondary Mesh Code"] = df["Secondary Mesh Code"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
