#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01b/kumamoto_road_centerlines_2024_preprocessed.parquet
Output: data/processed/road_centerlines_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01b/kumamoto_road_centerlines_2024_preprocessed.parquet"
dst = ROOT / "data/processed/road_centerlines_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Road Centerline Type Code": "Road Centerline Type Code",
    "Road Category Code": "Road Category Code",
    "Road State Code": "Road State Code",
    "Vertical Level": "Vertical Level",
    "Width Category Code": "Width Category Code",
    "Toll Category Code": "Toll Category Code",
    "Secondary Mesh Code": "Secondary Mesh Code",
    "Geometry": "Geometry",
    "Road Centerline Type": "Road Centerline Type",
    "Road Category": "Road Category",
    "Road State": "Road State",
    "Width Category": "Width Category",
    "Toll Category": "Toll Category",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Secondary Mesh Code
df["Secondary Mesh Code"] = df["Secondary Mesh Code"].str.strip()
# Road Centerline Type
df["Road Centerline Type"] = df["Road Centerline Type"].str.strip()
# Road Category
df["Road Category"] = df["Road Category"].str.strip()
# Road State
df["Road State"] = df["Road State"].str.strip()
# Width Category
df["Width Category"] = df["Width Category"].str.strip()
# Toll Category
df["Toll Category"] = df["Toll Category"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
