#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01b/kumamoto_fire_stations_2012_preprocessed.parquet
Output: data/processed/fire_dispatch_bases_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01b/kumamoto_fire_stations_2012_preprocessed.parquet"
dst = ROOT / "data/processed/fire_dispatch_bases_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Fire Facility Name": "Fire Base Name",
    "Municipality Code": "Municipality Code",
    "Fire Facility Type Code": "Fire Base Type Code",
    "Address": "Fire Base Address",
    "Geometry": "Geometry",
    "Fire Facility Type": "Fire Base Type",
    "Candidate Dispatch Base": "Candidate Dispatch Base",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Fire Base Name
df["Fire Base Name"] = df["Fire Base Name"].str.strip()
# Municipality Code
df["Municipality Code"] = df["Municipality Code"].str.strip()
# Fire Base Address
df["Fire Base Address"] = df["Fire Base Address"].str.strip()
# Fire Base Type
df["Fire Base Type"] = df["Fire Base Type"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
