#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01/kumamoto_population_mesh_125m_preprocessed.parquet
Output: data/processed/population_mesh_125m_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01/kumamoto_population_mesh_125m_preprocessed.parquet"
dst = ROOT / "data/processed/population_mesh_125m_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Mesh Code": "Mesh Code",
    "geometry": "Geometry",
    "Disclosure Group Code": "Disclosure Group Code",
    "Disclosure Group Size": "Disclosure Group Size",
    "Disclosure Status": "Disclosure Status",
    "Aggregation Destination Mesh Code": "Aggregation Destination Mesh Code",
    "Aggregated Source Mesh Codes": "Aggregated Source Mesh Codes",
    "Total Population": "Total Population",
    "Total Households": "Total Households",
    "General Households": "General Households",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Mesh Code
df["Mesh Code"] = df["Mesh Code"].str.strip()
# Disclosure Group Code
df["Disclosure Group Code"] = df["Disclosure Group Code"].str.strip()
# Aggregation Destination Mesh Code
df["Aggregation Destination Mesh Code"] = df["Aggregation Destination Mesh Code"].str.strip()
# Aggregated Source Mesh Codes
df["Aggregated Source Mesh Codes"] = df["Aggregated Source Mesh Codes"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
