#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01/kumamoto_emergency_evacuation_sites_geospatial_preprocessed.parquet
Output: data/processed/emergency_evacuation_sites_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01/kumamoto_emergency_evacuation_sites_geospatial_preprocessed.parquet"
dst = ROOT / "data/processed/emergency_evacuation_sites_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Common ID": "Evacuation Site ID",
    "Facility Name": "Evacuation Site Name",
    "Earthquake": "Earthquake Designation",
    "Large-Scale Fire": "Large-Scale Fire Designation",
    "Same Address as Designated Shelter": "Same Address as Designated Shelter",
    "geometry": "Geometry",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Evacuation Site ID
df["Evacuation Site ID"] = df["Evacuation Site ID"].str.strip()
# Evacuation Site Name
df["Evacuation Site Name"] = df["Evacuation Site Name"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
