#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01b/kumamoto_emergency_transport_roads_2024_preprocessed.parquet
Output: data/processed/emergency_transport_roads_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01b/kumamoto_emergency_transport_roads_2024_preprocessed.parquet"
dst = ROOT / "data/processed/emergency_transport_roads_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Emergency Road Class Code": "Emergency Road Class Code",
    "Road Type Code": "Emergency Road Type Code",
    "Route Name": "Route Name",
    "Route ID": "Route ID",
    "Branch ID": "Branch ID",
    "Service Status": "Emergency Road Service Status",
    "Geometry": "Geometry",
    "Emergency Road Class": "Emergency Road Class",
    "Road Type": "Emergency Road Type",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Route Name
df["Route Name"] = df["Route Name"].str.strip()
# Route ID
df["Route ID"] = df["Route ID"].str.strip()
# Branch ID
df["Branch ID"] = df["Branch ID"].str.strip()
# Emergency Road Service Status
df["Emergency Road Service Status"] = df["Emergency Road Service Status"].str.strip()
# Emergency Road Class
df["Emergency Road Class"] = df["Emergency Road Class"].str.strip()
# Emergency Road Type
df["Emergency Road Type"] = df["Emergency Road Type"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
