#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01/kumamoto_service_disruption_snapshots_preprocessed.parquet
Output: data/processed/service_disruptions_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01/kumamoto_service_disruption_snapshots_preprocessed.parquet"
dst = ROOT / "data/processed/service_disruptions_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Disruption Snapshot ID": "Disruption Snapshot ID",
    "Observation Time": "Observation Time",
    "Geographic Level": "Geographic Level",
    "Municipality": "Municipality",
    "Disruption Type": "Disruption Type",
    "Service Status": "Service Status",
    "Reported Municipality Count": "Reported Municipality Count",
    "Reported Affected Households": "Reported Affected Households",
    "Reported Affected People": "Reported Affected People",
    "Observed Power Outage Customers": "Observed Power Outage Customers",
    "Observed Water Outage Households": "Observed Water Outage Households",
    "Evidence Tier": "Evidence Tier",
    "Verification Status": "Verification Status",
    "Source Organization": "Source Organization",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Disruption Snapshot ID
df["Disruption Snapshot ID"] = df["Disruption Snapshot ID"].str.strip()
# Geographic Level
df["Geographic Level"] = df["Geographic Level"].str.strip()
# Municipality
df["Municipality"] = df["Municipality"].str.strip()
# Disruption Type
df["Disruption Type"] = df["Disruption Type"].str.strip()
# Service Status
df["Service Status"] = df["Service Status"].str.strip()
# Evidence Tier
df["Evidence Tier"] = df["Evidence Tier"].str.strip()
# Verification Status
df["Verification Status"] = df["Verification Status"].str.strip()
# Source Organization
df["Source Organization"] = df["Source Organization"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
