#!/usr/bin/env python3
"""Preprocessing script for data/raw/prior_projects/KE01/kumamoto_damage_evidence_registry_preprocessed.parquet
Output: data/processed/earthquake_damage_evidence_reference_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import geopandas as gpd
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/prior_projects/KE01/kumamoto_damage_evidence_registry_preprocessed.parquet"
dst = ROOT / "data/processed/earthquake_damage_evidence_reference_preprocessed.parquet"

# --- Load ---
try:
    df = gpd.read_parquet(src)
except ValueError:
    df = pd.read_parquet(src)
_source_geometry_name = df.geometry.name if isinstance(df, gpd.GeoDataFrame) else None

# --- Select and rename columns ---
rename_map = {
    "Evidence ID": "Evidence ID",
    "Event ID": "Event ID",
    "Observation Time": "Observation Time",
    "Municipality": "Municipality",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Coordinate Precision": "Coordinate Precision",
    "Coordinate Uncertainty m": "Coordinate Uncertainty (m)",
    "Evidence Tier": "Evidence Tier",
    "Verification Status": "Verification Status",
    "Asset Type": "Asset Type",
    "Observed Damage Type": "Observed Damage Type",
    "Structural Damage Class": "Structural Damage Class",
    "Reported Affected Asset Count": "Reported Affected Asset Count",
    "Place Description": "Place Description",
    "Source Organization": "Source Organization",
    "Source Type": "Source Type",
    "Source Report Number": "Source Report Number",
    "Source Page": "Source Page",
    "Source URL": "Source URL",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)
if isinstance(df, gpd.GeoDataFrame) and _source_geometry_name in rename_map:
    df = df.set_geometry(rename_map[_source_geometry_name])

# --- Variable-level preprocessing ---
# Evidence ID
df["Evidence ID"] = df["Evidence ID"].str.strip()
# Event ID
df["Event ID"] = df["Event ID"].str.strip()
# Municipality
df["Municipality"] = df["Municipality"].str.strip()
# Coordinate Precision
df["Coordinate Precision"] = df["Coordinate Precision"].str.strip()
# Evidence Tier
df["Evidence Tier"] = df["Evidence Tier"].str.strip()
# Verification Status
df["Verification Status"] = df["Verification Status"].str.strip()
# Asset Type
df["Asset Type"] = df["Asset Type"].str.strip()
# Observed Damage Type
df["Observed Damage Type"] = df["Observed Damage Type"].str.strip()
# Structural Damage Class
df["Structural Damage Class"] = df["Structural Damage Class"].str.strip()
# Place Description
df["Place Description"] = df["Place Description"].str.strip()
# Source Organization
df["Source Organization"] = df["Source Organization"].str.strip()
# Source Type
df["Source Type"] = df["Source Type"].str.strip()
# Source URL
df["Source URL"] = df["Source URL"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
